[package]
name = "rusted_shut"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
semver = { version = "1.0.23", features = ["serde"] }
thiserror = "2.0.4"
bon = "3.3.0"
walkdir = "2.5.0"